44_杨信 第二课作业
Guigulive/Team-E pull request #14
Opened 2018-03-15 10:41 UTC by xyang0917

2018-03-16 13:38 UTC, hezhihua81 requested changes
你并没有充分利用所定义的 totalSalary 这个状态变量。代码并没有得到优化。

2018-03-18 08:14 UTC, xyang0917 reviewed
已修改

2018-03-21 13:10 UTC, hezhihua81 requested changes
1. changePaymemntAddress:   var employee = employees[oldEmployeeId];
                                                    employees[newEmployeeId] = employee;
employee.id 还是老的
2. 附加题答案不正确

2018-03-22 13:59 UTC, xyang0917 commented
@hezhihua81 已修改

2018-03-26 03:44 UTC, hezhihua81 approved these changes
await 这种方式确定能测过么？

2018-03-26 03:44 UTC, merged