42 吴冠禧
Guigulive/Team-E pull request #32
Opened 2018-03-21 12:21 UTC by Rococolate

E42吴冠禧第三课作业

2018-03-21 13:55 UTC, hezhihua81 requested changes
changePaymentAddress： employees 这个mapping 里的key没有改成新的 aid

2018-03-24 15:43 UTC, Rococolate commented
第三课作业修改，第四课作业提交

2018-03-26 03:54 UTC, Rococolate commented
麻烦助教看看

2018-03-26 03:57 UTC, hezhihua81 approved these changes

2018-03-26 03:58 UTC, merged